trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- task: AppCenterTest@1
  inputs:
    appFile: '../virtuoso.apk'
    artifactsDirectory: '$(Build.ArtifactStagingDirectory)/AppCenterTest'
    frameworkOption: 'appium'
    appiumBuildDirectory: 'target/upload'
    credentialsOption: 'inputs'
    username: 'lti.qa001'
    password: 'Ashok2415'
    appSlug: 'lti.qa001/SampleAndroidApp'
    devices: '457b16d9'
    localeOption: 'en_US'