trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- script: appcenter login --token 5c73bb7b64b6a3e8f6fb5baba9fd479d3a891881
  displayName: 'Run a one-line script'
  

- script: |
    artifactsDirectory: '$(Build.ArtifactStagingDirectory)'
    appcenter test run appium --app "lti.qa001/SampleAndroidApp" --devices 457b16d9 --app-path $(Build.ArtifactStagingDirectory)/virtuosoAutomation/src/test/resources/virtuoso.apk  --test-series "master" --locale "en_US" --build-dir target/upload
  displayName: 'Run a multi-line script'
