trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- task: AppCenterTest@1
  inputs:
    appFile: '**/*.apk'
    artifactsDirectory: '$(Build.ArtifactStagingDirectory)/AppCenterTest'
    frameworkOption: 'appium'
    appiumBuildDirectory: 'target/upload'
    credentialsOption: 'serviceEndpoint'
    serverEndpoint: 'DemoAppCenterAccess'
    appSlug: 'lti.qa001/SampleAndroidApp'
    devices: '457b16d9'
    localeOption: 'en_US'
