# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


stages:
- stage: Test
  jobs:
  - job: TestOnMac
    steps:
    - script: echo "Executing Shell Scripting"
              cd $(echo ${VIRTUOSO_PROJECT_DIR} | tr -d '\r')
              mvn -DskipTests -P prepare-for-upload package
              echo "Executing in AppCenter"
              appcenter test run appium --app "VirtuosoTest/Virtuoso-Android" --devices "VirtuosoTest/demodevices" --app-path $(echo ${VIRTUOSO_PROJECT_DIR} | tr -d '\r')/src/test/resources/virtuoso.apk --test-series "login" --locale "en_US" --build-dir target/upload
#  - job: TestOnLinux
#    steps:
#    - script: echo Testing on Linux!
