# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- script: appcenter login --token 5c73bb7b64b6a3e8f6fb5baba9fd479d3a891881
  displayName: 'Run a one-line script'
  

- task: AppCenterTest@1
  inputs:
    appFile: '**/*.apk'
    artifactsDirectory: '$(Build.ArtifactStagingDirectory)/AppCenterTest'
    frameworkOption: 'appium'
    appiumBuildDirectory: 'target/upload'
    credentialsOption: 'inputs'
    appSlug: 'lti.qa001/SampleAndroidApp'
    devices: '457b16d9'
    localeOption: 'en_US'


  # appcenter test run appium --app "VirtuosoTest/Virtuoso-Android" --devices "VirtuosoTest/demodevices" --app-path pathToFile.apk  --test-series "login" --locale "en_US" --build-dir target/upload

# appcenter test run appium --app "lti.qa001/SampleAndroidApp" --devices 457b16d9 --app-path pathToFile.apk  --test-series "master" --locale "en_US" --build-dir target/upload
