# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- script: appcenter login --token 5c73bb7b64b6a3e8f6fb5baba9fd479d3a891881
  displayName: 'Run a one-line script'
  

- script: |
    path: PutMyCodeHere
    appcenter test run appium --app "VirtuosoTest/Virtuoso-Android" --devices "VirtuosoTest/demodevices" --app-path PutMyCodeHere/src/test/resources/virtuoso.apk  --test-series "login" --locale "en_US" --build-dir target/upload
  displayName: 'Run a multi-line script'


  # appcenter test run appium --app "VirtuosoTest/Virtuoso-Android" --devices "VirtuosoTest/demodevices" --app-path pathToFile.apk  --test-series "login" --locale "en_US" --build-dir target/upload
