trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- task: AppCenterTest@1
  inputs:
    appFile: '**/*.apk'
    artifactsDirectory: '$(Build.ArtifactStagingDirectory)/AppCenterTest'
    frameworkOption: 'appium'
    appiumBuildDirectory: 'target/upload'
    credentialsOption: 'inputs'
    username: 'lti.qa001'
    password: '34345626-cb6a-473a-be30-3b4acf09cc46'
    appSlug: 'lti.qa001/SampleAndroidApp'
    devices: '457b16d9'
    localeOption: 'en_US'
